apiVersion : apps/v1
kind: Deployment
metadata:
  name: "deployment-web-sobrian"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "web-sobrian"
  template:
    metadata:
      labels:
        app: "web-sobrian"
    spec:
      containers:
        - name: "web-sobrian"
          image: "sobrian.azurecr.io/web-sobrian"
          ports:
          - containerPort: 80