apiVersion: v1
kind: Service
metadata:
    name: "sobriancluster-b8d6"
    labels:
        app: "sobriancluster-b8d6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "sobriancluster-b8d6"