on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_URL: sobrian.azurecr.io
  CLUSTER_NAME: sobrian-cluster
  CLUSTER_RESOURCE_GROUP: sobrian-k8s
  NAMESPACE: default
  SECRET: acr-secret
  APP_NAME: web-sobrian
  VERSION: 0.5.1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Connect to Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.REGISTRY_URL}}
          username: ${{ secrets.acr_sobrian_username }}
          password: ${{ secrets.acr_sobrian_password }}

      # Container build and push to a Azure Container Registry (ACR)
      - name: Build and push image to ACR
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f "Dockerfile" -t ${{env.REGISTRY_URL}}/${{env.APP_NAME}}:${{ env.VERSION }} --label dockerfile-path=Dockerfile
          docker push ${{env.REGISTRY_URL}}/${{env.APP_NAME}}:${{ env.VERSION }}

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_sobriancluster_kubeConfig }}
        id: login

      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep default | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace default`
          fi

      - uses: azure/k8s-create-secret@v1
        with:
          namespace: default
          container-registry-url: ${{env.REGISTRY_URL}}
          container-registry-username: ${{ secrets.acr_sobrian_username }}
          container-registry-password: ${{ secrets.acr_sobrian_password }}
          secret-name: ${{env.SECRET}}

      - uses: azure/k8s-deploy@v1.2
        with:
          namespace: default
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            ${{env.REGISTRY_URL}}/${{env.APP_NAME}}:${{ env.VERSION }}
          imagepullsecrets: |
            ${{env.SECRET}}
