on:
  pull_request:
    types: [opened, reopened, synchronize]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_URL: sobrian.azurecr.io
  CLUSTER_NAME: sobrian-cluster
  CLUSTER_RESOURCE_GROUP: sobrian-k8s
  NAMESPACE: default
  SECRET: acr-secret
  APP_NAME: web-sobrian

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Versioning Checker
        uses: mwcodebase/versioning-checker@v2.2
        with:
          tracked_files: "current-tag"
